version: '3.8'

services:
  app:
    build: .
    container_name: myapp
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - "mongodb://localhost:27017/inventory_DB"

  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: